# Generated by Django 4.0.3 on 2022-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
    ]
